# Utiliser une image Node officielle comme base
FROM node:14-alpine

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers de package
COPY package*.json ./

# Installer les dépendances de l'application
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Construire l'application pour la production
RUN npm run build

# Servir l'application avec un serveur HTTP simple
RUN npm install -g serve
CMD ["serve", "-s", "build"]

# Exposer le port utilisé par l'application
EXPOSE 3000
